provider:
  oanda:
    uri_stream: https://stream-fxpractice.oanda.com/v3/accounts/<account_id>/pricing/stream
    account_id: 101-004-5956477-001
    instruments: instruments=EUR_USD
    token: 0b401ca1950dc6078b8805d903a3b7f7-228a67e3d766c8faf7ebaae633a96637

